### ISSUE TITLE
User page field needs a little more height for font

### ISSUE THREAD

**Issue by dajare** [pawedWolf/wolfcms-fox-admintheme#1]
Brilliant admin theme! A couple glitches that are very small - here's one:

The field for the user email is just a little too short to fit the font:

[![too small][1]][2]

A bit more height would make space to the "descender" letters don't get cropped. (I'm on OSX 10.10.5 at the moment, by the way - I haven't tested on a different OS - but will soon!)

[1]: http://i.imgur.com/uRt0WOnm.png "Click for full size image"
[2]: http://i.imgur.com/uRt0WOn.png

**Comment by SamBrishes** [comment]
Thanks, i know that this issue appears also in Firefox (on Windows Vista/7). ^^

I will fix this issue, after I completely set up my computer and installed my work environment. (I had some troubles with my pc).

Thanks for the Bug Report!

**Comment by SamBrishes** [comment]
Fixed in Version 0.1.1!
