### ISSUE TITLE
Notification popups : page shifts when they disappear

### ISSUE THREAD

**Issue by dajare** [pawedWolf/wolfcms-fox-admintheme#2]
The notification popups come between the menu bar and the page title. When they disappear, the page moves up. If you're working quickly, you can end up clicking on the wrong thing!

Would it be worth giving the notifications/alerts an absolute (?) placement (maybe in the free space beside the `<h1>...</h1>` element?) so that the page stays stable after the message disappears?

**Comment by SamBrishes** [comment]
Sure, i will move the popup container beside the h1 element in the next patch.

Thanks.

**Comment by dajare** [comment]
Thanks, Sam! :+1:

**Comment by SamBrishes** [comment]
Fixed / Added in Version 0.1.1
